### ISSUE TITLE
Am I the only one who has this problem?

### ISSUE THREAD

**Issue by vkamz597** [Taylor-pm-pl/SimplySickles#2]
I received what is displayed here and applied it, but I am experiencing the following problems
 
 https://poggit.pmmp.io/p/SimplySickles/2.0.0
 
 Error: "Class "libCustomPack\libCustomPack" not found" (EXCEPTION) in "plugins/SimplySickles-API-5/src/taylordevs/SimplySickles/SimplySickles" at line 26
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginBase(118): taylordevs\SimplySickles\SimplySickles->onEnable()
  #1 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #2 pmsrc/src/Server(1388): pocketmine\plugin\PluginManager->enablePlugin(object taylordevs\SimplySickles\SimplySickles#61136)
  #3 pmsrc/src/Server(1032): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#40746)
  #4 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[14] /home/user/pm/, string[22] /home/user/pm/plugins/)
  #5 pmsrc/src/PocketMine(357): pocketmine\server()
  #6 pmsrc(11): require(string[58] phar:///home/user/pm/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by taylordevs** [comment]
> I received what is displayed here and applied it, but I am experiencing the following problems
> 
> https://poggit.pmmp.io/p/SimplySickles/2.0.0
> 
> Error: "Class "libCustomPack\libCustomPack" not found" (EXCEPTION) in "plugins/SimplySickles-API-5/src/taylordevs/SimplySickles/SimplySickles" at line 26 --- Stack trace --- #0 pmsrc/src/plugin/PluginBase(118): taylordevs\SimplySickles\SimplySickles->onEnable() #1 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true) #2 pmsrc/src/Server(1388): pocketmine\plugin\PluginManager->enablePlugin(object taylordevs\SimplySickles\SimplySickles#61136) #3 pmsrc/src/Server(1032): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#40746) #4 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[14] /home/user/pm/, string[22] /home/user/pm/plugins/) #5 pmsrc/src/PocketMine(357): pocketmine\server() #6 pmsrc(11): require(string[58] phar:///home/user/pm/PocketMine-MP.phar/src/PocketMine.php) --- End of exception information ---

Install [libCustomPack](https://github.com/jasonw4331/libCustomPack) virion or download plugin at [poggit](https://poggit.pmmp.io/p/SimplySickles)

**Comment by vkamz597** [comment]
I definitely downloaded from poggit and still get the same error I also tried adding virion as a solution to that, but it was not solved
![image](https://github.com/Taylor-pm-pl/SimplySickles/assets/82744478/9c14bde8-41d3-44c5-b47c-f9e2ed02b59a)

**Comment by vkamz597** [comment]
Customies v1.3.0을(를) 불러오는 중입니다
[14:10:40.004] [Server thread/INFO]: DEVirion v1.3.0을(를) 불러오는 중입니다
[14:10:40.025] [Server thread/INFO]: [DEVirion] Loading virion libCustomPack v1.0.1 by jasonw4331 (antigen: libCustomPack)
[14:10:40.025] [Server thread/WARNING]: [DEVirion] Virions should be bundled into plugins, not redistributed separately! Do NOT use DEVirion on production servers!!
[14:10:40.041] [Server thread/INFO]: SimplySickles v2.0.0을(를) 불러오는 중입니다
[14:10:40.049] [Server thread/INFO]: DEVirion v1.3.0을(를) 사용하도록 설정하는 중입니다
[14:10:40.259] [Server thread/INFO]: "world" 세계를 준비하는 중입니다
[14:10:40.296] [Server thread/INFO]: Customies v1.3.0을(를) 사용하도록 설정하는 중입니다
[14:10:40.302] [Server thread/INFO]: SimplySickles v2.0.0을(를) 사용하도록 설정하는 중입니다
[14:10:40.303] [Server thread/CRITICAL]: Error: "Class "taylordevs\SimplySickles\libs\libCustomPack\libCustomPack" not found" (EXCEPTION) in "plugins/SimplySickles.phar/src/taylordevs/SimplySickles/SimplySickles" at line 30
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginBase(118): taylordevs\SimplySickles\SimplySickles->onEnable()
  #1 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #2 pmsrc/src/Server(1388): pocketmine\plugin\PluginManager->enablePlugin(object taylordevs\SimplySickles\SimplySickles#40742)
  #3 pmsrc/src/Server(1032): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#40703)
  #4 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[29] C:\Users\user\Desktop\Server\, string[37] C:\Users\user\Desktop\Server\plugins\)
  #5 pmsrc/src/PocketMine(357): pocketmine\server()
  #6 pmsrc(11): require(string[73] phar://C:/Users/user/Desktop/Server/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
